name: Release

on:
  push:
    branches:
      - main # Assuming you're using the main branch; change if necessary

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install required libraries
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev

    - name: Install Mingw-w64 Toolchain
      run: sudo apt-get install -y mingw-w64

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    #- name: Build
     # run: |
      #  GOOS=windows GOARCH=amd64 go build -v -o GoPanzer.exe ./...
    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -v -o GoPanzer.exe ./...

    - name: Create Git Tag
      id: create_tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        DATETIME=$(date +'%Y-%m-%d-%H%M%S')
        git tag "release-$DATETIME"
        git push https://${{ secrets.PAT }}@github.com/${{ github.repository }} "release-$DATETIME"
        echo "tag_name=release-$DATETIME" >> $GITHUB_ENV

    - name: Archive Executable and Assets into ZIP
      run: zip -r GoPanzer_${{env.tag_name}}.zip GoPanzer.exe Assets/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.tag_name }}
        release_name: Release ${{ env.tag_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Upload Release ZIP Archive
      id: upload-release-archive
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./GoPanzer_${{env.tag_name}}.zip
        asset_name: GoPanzer_${{env.tag_name}}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
